export default {
  TextInput:         'TextInput',
  TextArea:          'TextArea',
  TextEditor:        'TextEditor',
  NumberInput:       'NumberInput',
  Bool:              'Bool',
  Radios:            'Radios',
  ColorSwatchRadios: 'ColorSwatchRadios',
  Select:            'Select',
  MediaPicker:       'MediaPicker',
  NestedBlock:       'NestedBlock',
  Repeater:          'Repeater',
  Searchable:        'Searchable',
  ErrorField:        'ErrorField',
}
